README.md
examples/storage.py
scrapy_playwright/handler.py
tests/test_playwright_requests.py

Response.ip_address attribute

---

scrapy_playwright/handler.py

Requested at #66.
Not added in the `Response.certificate` attribute because the full certificate is not available, this is just some information _about_ the certificate.

Response security details

---

scrapy_playwright/handler.py
tests/test_page_coroutines.py

- Warn (and skip) if a value in `playwright_page_coroutines` is not a `PageCoroutine` object
- Also accept non-awaitable calls (not strictly only coroutines anymore but hey, why not?)

PageCoroutine checks

---

README.md
changelog.md
scrapy_playwright/handler.py
tests/test_browser_contexts.py

Deprecated since July 16th, 2021 (https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.4)

Remove deprecated PLAYWRIGHT_CONTEXT_ARGS setting

---

scrapy_playwright/handler.py
tests/test_playwright_requests.py

Closes #15
In #15, a `TimeoutError` causes the following:
* [This line](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/scrapy_playwright/handler.py#L241) fails ([here](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/scrapy_playwright/handler.py#L252), to be precise), so the `except` block closes the page which handled the request to avoid having unused pages consuming memory
* Then [this line](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/scrapy_playwright/handler.py#L370) fails with the "Target page, context or browser has been closed" message, because the page was indeed closed
The first exception can be handled with a [request errback](https://docs.scrapy.org/en/latest/topics/request-response.html#using-errbacks-to-catch-exceptions-i …

Warn on failed requests

---

README.md
scrapy_playwright/handler.py

Set playwright_page request meta key early

---

README.md
changelog.md
scrapy_playwright/handler.py
scrapy_playwright/headers.py
setup.py
tests/test_headers.py
tests/test_playwright_requests.py
tox.ini

See https://playwright.dev/python/docs/release-notes#version-115
Tasks:

Use new headers API from Playwright 1.15

---

scrapy_playwright/handler.py
tests/test_headers.py

Request headers accessed in callbacks do not match actual headers sent to the target website when setting `PLAYWRIGHT_PROCESS_REQUEST_HEADERS=None`:
```python
import json
from scrapy import Spider, Request
class HeadersSpider(Spider):
name = "headers"
custom_settings = {
"TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
"DOWNLOAD_HANDLERS": {
"https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
},
"PLAYWRIGHT_PROCESS_REQUEST_HEADERS": None,
"USER_AGENT": "Overridden user agent",
}
def start_requests(self):
yield Request(
url="https://httpbin.org/headers",
meta={"playwright": True},
)
def parse(self, response):
actual_user_agent = json.loads(response.css("pre::text").get())["headers"]["User-Agent"]
print("Actual user agent: ", actual_user_agent) …
```

Always override request headers

---

scrapy_playwright/handler.py
tests/test_playwright_requests.py

Closes #10, closes #102.
I'm still not entirely sure why the issues mentioned above occur, however this should provide a reasonable way for the crawl to proceed without errors in such cases.
From the [upstream docs on `Page.goto`](https://playwright.dev/python/docs/api/class-page#page-goto):
> The method either throws an error or returns a main resource response. The only exceptions are navigation to about:blank or navigation to the same URL with a different hash, which would succeed and return null.

Don't break if Page.goto returns None

---

README.md
changelog.md
scrapy_playwright/handler.py
scrapy_playwright/headers.py
scrapy_playwright/page.py
tests/test_headers.py
tests/test_page_methods.py

Removed following the [deprecation policy](https://github.com/scrapy-plugins/scrapy-playwright#deprecation-policy):
* `scrapy_playwright.headers.use_playwright_headers` function, deprecated since [`v0.0.16`](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.16)
* `scrapy_playwright.page.PageCoroutine` class, deprecated since [`v0.0.14`](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.14)
* `playwright_page_coroutines` Request meta key, deprecated since [`v0.0.14`](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.14)

Remove deprecated code

---

README.md
changelog.md
examples/init_page.py
pylintrc
scrapy_playwright/handler.py
tests/test_playwright_requests.py

Closes #25
Add `playwright_page_init_callback` request meta key.
Tasks:

Page init callback

---

scrapy_playwright/handler.py
tests/mockserver.py
tests/test_playwright_requests.py

Closes #137
Keys taken from the [upstream implementation](https://github.com/scrapy/scrapy/blob/2.7.1/scrapy/downloadermiddlewares/redirect.py#L49-L52) (except for `redirect_ttl`, there is no way to limit redirects in Playwright AFAICT).

Set redirect meta

---

pylintrc
scrapy_playwright/handler.py
tests/test_playwright_requests.py

Closes #100, closes #119, closes #143
I discovered the method for some navigation requests was incorrectly being overridden from POST to GET. This piece of code is there only because with `Page.goto` one can only trigger GET requests directly, however the URLs for the Playwright and Scrapy requests were not the same so the requests did not match each other.

Fix request method override

---

scrapy_playwright/handler.py
tests/test_playwright_requests.py

Closes #155
Log records emitted after the spider is opened will have a `spider` attribute.
Pattern taken from https://docs.python.org/3/library/logging.html#logrecord-objects.

Set spider attribute on log records

---

scrapy_playwright/handler.py

Fixes #176
Introduced at #144, seems like both checks are necessary.

Override method only for navigation requests

---

scrapy_playwright/handler.py

Pass spider argument to _create_browser_context

---

README.md
examples/contexts.py
tests/test_browser_contexts.py

Readme: note about avoid race conditions & memory leaks when closing contexts

---

scrapy_playwright/_utils.py
scrapy_playwright/handler.py
tests/__init__.py
tests/site/redirect.html
tests/test_encoding.py
tests/test_playwright_requests.py
tests/test_utils.py

Closes #217, closes #186
I wanted to start simple so there's only one retry. This might be a bit naive, perhaps some exponential backoff retrying could be added in the future if this continues to be an issue.

Retry page.content if necessary

---

scrapy_playwright/handler.py
scrapy_playwright/headers.py

Fixes #181
* Scrapy headers were being updated for every Playwright request, they should only be updated for the Playwright request that corresponds to the original Scrapy one
* Referer header from the Playwright request was not added to the output of scrapy_playwright.headers.use_scrapy_headers

Do not override headers with values from asset requests

---

.github/workflows/checks.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

CI: bump actions version

---

.github/workflows/checks.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

CI: Update actions/setup-python (v4 -> v5)

---

scrapy_playwright/_utils.py
scrapy_playwright/handler.py
tests/__init__.py
tests/tests_twisted/test_mixed_requests.py

Closes #282
Alternative approach to #285
This yields full concurrency (`'playwright/page_count/max_concurrent': 32` in stats) with the sample spider from #285:
```python
import scrapy
class DelayTest(scrapy.Spider):
name = "delay"
custom_settings = {
"TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
"DOWNLOAD_HANDLERS": {
"https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
},
"PLAYWRIGHT_MAX_PAGES_PER_CONTEXT": 32,
"CONCURRENT_REQUESTS_PER_IP": 32,
"CONCURRENT_REQUESTS_PER_DOMAIN": 32,
"CONCURRENT_REQUESTS": 32,
"PLAYWRIGHT_LAUNCH_OPTIONS": {"headless": False},
}
def start_requests(self):
for i in range(32):
yield scrapy.Request(
url=f"https://httpbin.org/delay/1?i={i}",
meta={"playwright": True},
)
def parse(self, response): …
```

Improve concurrency on Windows

---

scrapy_playwright/handler.py
tests/mockserver.py
tests/tests_asyncio/test_playwright_requests.py

Fix freezing on responses with status 204

---

scrapy_playwright/handler.py
tests/tests_asyncio/test_playwright_requests.py

Closes #271
We need to identify the Playwright request that matches the Scrapy request in order to override method and body if necessary.
Checking the URL and `Request.is_navigation_request()` is not enough, e.g. requests produced by submitting forms can produce false positives.
Let's track only the first request that matches the above conditions.

Override method and/or body only for the first matching request

---

scrapy_playwright/handler.py
tests/tests_asyncio/test_playwright_requests.py

Closes https://github.com/scrapy-plugins/scrapy-playwright/issues/335

Only register request and response loggers when needed

---

pylintrc
scrapy_playwright/_utils.py

Replace scrapy.utils.defer.deferred_from_coro
